[2022-11-29T17:21:35.761+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hashtag_generator.create_table_postgres manual__2022-11-29T17:21:34.975502+00:00 [queued]>
[2022-11-29T17:21:35.770+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hashtag_generator.create_table_postgres manual__2022-11-29T17:21:34.975502+00:00 [queued]>
[2022-11-29T17:21:35.770+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:21:35.770+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T17:21:35.770+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:21:35.781+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table_postgres> on 2022-11-29 17:21:34.975502+00:00
[2022-11-29T17:21:35.785+0000] {standard_task_runner.py:55} INFO - Started process 1246 to run task
[2022-11-29T17:21:35.788+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hashtag_generator', 'create_table_postgres', 'manual__2022-11-29T17:21:34.975502+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/hashtag_generator.py', '--cfg-path', '/tmp/tmpth6q12h9']
[2022-11-29T17:21:35.789+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask create_table_postgres
[2022-11-29T17:21:35.843+0000] {task_command.py:376} INFO - Running <TaskInstance: hashtag_generator.create_table_postgres manual__2022-11-29T17:21:34.975502+00:00 [running]> on host 1f1c6b02f2ce
[2022-11-29T17:21:35.870+0000] {abstractoperator.py:421} ERROR - Exception rendering Jinja template for task 'create_table_postgres', field 'sql'. Template: 'scripts/postgres_scripts/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 468, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/postgres_scripts/create_table.sql
[2022-11-29T17:21:35.871+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1193, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 468, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scripts/postgres_scripts/create_table.sql
[2022-11-29T17:21:35.877+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=hashtag_generator, task_id=create_table_postgres, execution_date=20221129T172134, start_date=20221129T172135, end_date=20221129T172135
[2022-11-29T17:21:35.887+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task create_table_postgres (scripts/postgres_scripts/create_table.sql; 1246)
[2022-11-29T17:21:35.919+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T17:21:35.933+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
